
name: Build
on:
  push:
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Configure and Build banking
        run: |
          cd code
          cmake -B build
          cmake --build build
          build/main

      - name: Upload Artifact
        run: |
          mkdir artifacts
          mv _build/*.tar.gz artifacts
          tree artifacts
      
      - name: Test
        run: |
          cmake -B build
          cmake --build build
          build/test_app
